version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
  mongo-express:
     image: mongo-express
     container_name: mongo-express
     restart: always
     ports:
       - 8081:8081
     environment:
       - ME_CONFIG_MONGODB_ADMINUSERNAME=user
       - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
       - ME_CONFIG_MONGODB_SERVER=mongodb
  spr-mongodb-app:
      image: mongodb
      container_name: mongodb
      build:
        context: .
        target: development
      ports:
        - 8000:8000
      environment:
        - SERVER_PORT=8000
      volumes:
        - ./:/app
      depends_on:
        - mongodb 
volumes:
  data: {}
networks:
  default:
     name: spring_mongodb_network        

      
      
  