#Configuration for accessing data with MySQL
#The default database is H2. Consequently, you want to use other database,
# must define the connection attributes 


#--------      
server:
  port: 8081
#--------      
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hanh3533.
    url: jdbc:mysql://localhost:3306/demo_jwt
#--------    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true 
#--------      
logging:
  level:
    org:
      springframework:
        security: TRACE  
   
   
   
   
   

